adding check_install for quick_* files where necessary
hughjonesd/huxtable pull request #238
Opened 2023-02-19 03:01 UTC by reuning

I added some lines to check if the requisite packages are available for the `quick_*()` functions. I also indicated in the documentation what packages were needed. 

(I was showing students huxtable in a bootcamp and the error thrown about needing to install packages threw them, this might be unnecessary but thought it would be helpful).

2023-02-19 04:05 UTC, hughjonesd commented
Could you alter this to use huxtable's `assert_package`? This will be more consistent. 

Arguably assert_package could be replaced everywhere by the rlang function. That would be a different PR though.

2023-02-19 17:23 UTC, reuning commented
Sure, I switched it over to `assert_package()` for now. I dropped the check for flextable as I noticed that `as_flextable()` already does that and is called before additional flextable functons are called.

2023-02-20 11:08 UTC, hughjonesd requested changes
As the first argument to assert_package, use the name of calling function - the user won't know about e.g. `read_docx` but will know about `quick_docx`.

2023-02-20 11:08 UTC, hughjonesd commented
Don't worry about failing checks - that's not your fault

2023-02-20 13:15 UTC, reuning commented
That makes a lot more sense. Sorry about that. Given that I also added `assert_package()`calls for flextable to clarify why the user needs flextable. It might be unnecessary. Hopefully this is good to go now.

2023-02-20 14:10 UTC, merged

2023-02-20 14:10 UTC, hughjonesd commented
Thanks, merged!